# Determinan
1.   Cari fungsi untuk menghitung determinan dalam python



#Matriks A (2x2)

In [2]:
# importing Numpy package
import numpy as np

# creating a 2X2 Numpy matrix
n_array = np.array([[1, 0], [0, 1]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nDeterminant of given 2X2 matrix:")
print(int(det))


Numpy Matrix is:
[[1 0]
 [0 1]]

Determinant of given 2X2 matrix:
1


# Matriks B (3x3)

### Sifat 1 : determinan matrix identitas dengan ordo berapapun adalah 1

In [3]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[1, 0, 0],
					[0, 1, 0],
					[0, 0, 1]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nDeterminant of given 3X3 square matrix:")
print(int(det))


Numpy Matrix is:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Determinant of given 3X3 square matrix:
1


# Matriks C

In [4]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[1, 2, 1],
					[3, 1, 2],
					[2, 1, 2]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nDeterminant of given 3X3 square matrix:")
print(int(det))


Numpy Matrix is:
[[1 2 1]
 [3 1 2]
 [2 1 2]]

Determinant of given 3X3 square matrix:
-3


# Matriks D (dibalik barisnya dari matriks C)
### Sifat 2 : jika salah satu baris diubah nilai elemennya maka hasil determinannnya juga ikut berubah

In [5]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[3, 1, 2],
					[1, 2, 1],
					[2, 1, 2]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nDeterminant of given 3X3 square matrix:")
print(int(det))


Numpy Matrix is:
[[3 1 2]
 [1 2 1]
 [2 1 2]]

Determinant of given 3X3 square matrix:
3


# Matriks E (kelipatan dari baris ke-2 D)


### Sifat 3 : Jika suatu baris ataupun kolom merupakan kelipatan dari baris yang lain maka determinan matrix tersebut adalah 0 (baris 2 adalah kelipatan dari baris 1)


In [6]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[1, 2, 1],
					[2, 4, 2],
					[2, 1, 2]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nJika suatu baris adalah kelipatan dari baris yang lain maka determinan matrix tersebut adalah 0 \nbaris 2 adalah kelipatan dari baris 1 matriks D ")
print(int(det))


Numpy Matrix is:
[[1 2 1]
 [2 4 2]
 [2 1 2]]

Jika suatu baris adalah kelipatan dari baris yang lain maka determinan matrix tersebut adalah 0 
baris 2 adalah kelipatan dari baris 1 matriks D 
0


# Matriks F

In [7]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[1, 2, 1],
					[2, 4, 2],
					[2, 4, 2]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nJika suatu kolom adalah kelipatan dari kolom yang lain maka determinan matrix tersebut adalah 0 \nkolom 2 baris 3 adalah kelipatan dari kolom 2 baris 3 matriks E")
print(int(det))


Numpy Matrix is:
[[1 2 1]
 [2 4 2]
 [2 4 2]]

Jika suatu kolom adalah kelipatan dari kolom yang lain maka determinan matrix tersebut adalah 0 
kolom 2 baris 3 adalah kelipatan dari kolom 2 baris 3 matriks E
0


# Matriks G
### sifat 4 : Jika matrix tersebut adalah kelipatan sebanyak n * matrix maka untuk mencari determinan adalah (n^(sebanyak ordo)determinan matrix)contoh matrix g adalah kelipatan 2 kali dari matrix d : (2^3(det d))

In [8]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[6, 2, 4],
					[2, 4, 2],
					[4, 2, 4]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nMatriks G merupakan kelipatan 2 dari matriks D maka kesimpulannya (2^3(det d))")
print(int(det))


Numpy Matrix is:
[[6 2 4]
 [2 4 2]
 [4 2 4]]

Matriks G merupakan kelipatan 2 dari matriks D maka kesimpulannya (2^3(det d))
24


# Matriks H
### pembuktian sifat 4 dengan matriks 2x2

In [9]:
a = np.array([[3, 4],
					[2, 1]])
print("matriks a:")
print(a)

det = np.linalg.det(a)
print("determinan :")
print(det.round())

matriks a:
[[3 4]
 [2 1]]
determinan :
-5.0


In [10]:
# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[6, 8],
					[4, 2],])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# calculating the determinant of matrix
det = np.linalg.det(n_array)

print("\nDeterminant of given 3X3 square matrix:")
print(det.round())


Numpy Matrix is:
[[6 8]
 [4 2]]

Determinant of given 3X3 square matrix:
-20.0


### Sifat 5 : Jika terdapat matrix baru dengan nilai salah satu baris atau kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2*(determinan matrix)
contoh matrix i baris pertama adalah kelipatan 2 dari matrix a

contoh matrix j kolom pertama adalah kelipatan 2 dari matrix a

In [11]:
i = np.array([[6, 8],
					[2, 1]])

print("Matriks i :")
print(i)
print("sifat 5 : jika terdapat matrix baru dengan nilai salah satu baris adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2x(det a)")
det = np.linalg.det(i)
print("Determinan : ")
print(det.round())

Matriks i :
[[6 8]
 [2 1]]
sifat 5 : jika terdapat matrix baru dengan nilai salah satu baris adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2x(det a)
Determinan : 
-10.0


In [12]:
j = np.array([[6, 4],
					[4, 1]])
print("Matriks j :")
print(j)
print("sifat 6 : jika terdapat matrix baru dengan nilai salah satu kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2x(det a)")
det = np.linalg.det(j)
print("Determian : ")
print(det.round())

Matriks j :
[[6 4]
 [4 1]]
sifat 6 : jika terdapat matrix baru dengan nilai salah satu kolom adalah kelipatan 2 dari matrix sebelumnya maka dapat disimpulkan dengan 2x(det a)
Determian : 
-10.0


### Sifat 6 : Jika suatu matrix yang berasal dari penjumlahan matrix k dengan matrix a maka untuk mencari determinan cukup menjumlahkan hasil dari 2 determinan matrix tersebut

In [13]:
k = np.array([[4, 1],
					[2, 1]])
print("Matriks K : ")
print(k)

det = np.linalg.det(k)
print("Determinan : ")
print(det.round())

Matriks K : 
[[4 1]
 [2 1]]
Determinan : 
2.0


In [14]:
a = np.array([[3, 4],
					[2, 1]])
print("Matriks a :")
print(a)

det = np.linalg.det(a)
print("Determinan : ")
print(det.round())

Matriks a :
[[3 4]
 [2 1]]
Determinan : 
-5.0


In [15]:
l = np.array([[7, 5],
					[2, 1]])
print(l)
print("Matriks l : ")
print("determinan matriks a :2")
print("determinan matriks k :-5")
print("2+(-5)=-3")
det = np.linalg.det(l)
print("determinan :")
print(det.round())

[[7 5]
 [2 1]]
Matriks l : 
determinan matriks a :2
determinan matriks k :-5
2+(-5)=-3
determinan :
-3.0


### Sifat 7 : Jika ada matrix segitiga atas atau bawah maka determinan nya adalah perkalian anggota diagonal matrix tersebut

### jadi 1 x 2 x 5 = 10

In [16]:
m = np.array([[1, 2, 3],
					[0, 2, 1],
					[0, 0, 5]])
print("matriks m :")
print(m)
det = np.linalg.det(m)
print("Determinan : ")
print(det.round())

matriks m :
[[1 2 3]
 [0 2 1]
 [0 0 5]]
Determinan : 
10.0


### jadi 2 x 3 x 2 = 12

In [17]:
n = np.array([[2, 0, 0],
					[3, 3, 0],
					[1, 2, 2]])

print("matriks n :")
print(n)
det = np.linalg.det(n)
print("Determinan : ")
print(int(det))

matriks n :
[[2 0 0]
 [3 3 0]
 [1 2 2]]
Determinan : 
12


### Sifat 8 : untuk mencari determinan dari Hasil perkalian matrix O dengan matrix p yaitu dengan mengalikan determinan matrix O dan p contoh (det O = 1 , det p = 1 maka det q adalah 0)

In [18]:
O = np.array([[2, 1],
					[1, 1]])

print(O)
det = np.linalg.det(O)
print(int(det))

[[2 1]
 [1 1]]
1


In [19]:
p = np.array([[1, 1],
					[1, 1]])

print(p)
det = np.linalg.det(p)
print(int(det))

[[1 1]
 [1 1]]
0


In [20]:
q=O@p
print(q)
det = np.linalg.det(q)
print(int(det))

[[3 3]
 [2 2]]
0
