# Kofaktor

# Tugas Kofaktor matrix ordo 5x5
Matrix yang akan saya buat adalah matrix dengan ordo 5x5

ialah sebagai berikut
$$
A=\begin{bmatrix}
1 &2&1&1&1\\
2&1&3&1&1\\
3&2&3&2&2 \\
4&1&1&4&3\\
3&5&1&2&2
\end{bmatrix}
$$
Matrix ini akan saya jadikan invers, hal pertama yang akan cari adalah determinannya terlebih dahulu

Rumus Kofaktor=
$$
C_{ij} = (-1)^{i+j} * detA
$$

rumus det (pick one row or column) =
$$
a_{ij} * c_{ij} + a_{ij} * c_{ij} + a_{ij} * c_{ij} + a_{nn} * c_{nn}$$

rumus invers matrix =
$${ \frac{1}{detA}} * adj(a)$$

Mencari Adjoin =
$$adj(A) = (kof(A))^T$$

(adj(S) = Transpose dari setiap cofator-cofator Matrix)

In [ ]:
import numpy as np

matrix_A = np.array([[1,2,1,1,1],[2,1,3,1,1],[3,2,3,2,2],[4,1,1,4,3],[3,5,1,2,2]])
print(f"Matrix A: \n{matrix_A}")
det_Mat_A = np.linalg.det(matrix_A)
inv_Mat_A = np.linalg.inv(matrix_A)
print(f"pembuktian Determinan= {det_Mat_A}")
print(f"pembuktian Invers = \n{inv_Mat_A.round(1)}")
print()
print("="*50)
# kita mencari determinannya terlebih dahulu dengan Pick setiap row

A11 = np.array([[1,3,1,1],[2,3,2,2],[1,1,4,3],[5,1,2,2]])
A12 = np.array([[2,3,1,1],[3,3,2,2],[4,1,4,3],[3,1,2,2]])
A13 = np.array([[2,1,1,1],[3,2,2,2],[4,1,4,3],[3,5,2,2]])
A14 = np.array([[2,1,3,1],[3,2,3,2],[4,1,1,3],[3,5,1,2]])
A15 = np.array([[2,1,3,1],[3,2,3,2],[4,1,1,4],[3,5,1,2]])
A21 = np.array([[2,1,1,1],[2,3,2,2],[1,1,4,3],[5,1,2,2]])
A22 = np.array([[1,1,1,1],[3,3,2,2],[4,1,4,3],[3,1,2,2]])
A23 = np.array([[1,2,1,1],[3,2,2,2],[4,1,4,3],[3,5,2,2]])
A24 = np.array([[1,2,1,1],[3,2,3,2],[4,1,1,3],[3,5,1,2]])
A25 = np.array([[1,2,1,1],[3,2,3,2],[4,1,1,4],[3,5,1,2]])
A31 = np.array([[2,1,1,1],[1,3,1,1],[1,1,4,3],[1,1,2,2]])
A32 = np.array([[1,1,1,1],[2,3,1,1],[4,1,4,3],[3,1,2,2]])
A33 = np.array([[1,2,1,1],[2,1,1,1],[4,1,4,3],[3,1,2,2]])
A34 = np.array([[1,2,1,1],[2,1,3,1],[4,1,1,3],[3,1,1,2]])
A35 = np.array([[1,2,1,1],[2,1,3,1],[4,1,1,4],[3,1,1,2]])
A41 = np.array([[2,1,1,1],[1,3,1,1],[2,3,2,2],[5,1,2,2]])
A42 = np.array([[1,1,1,1],[2,3,1,1],[3,3,2,2],[3,1,2,2]])
A43 = np.array([[1,2,1,1],[2,1,1,1],[3,2,2,2],[3,5,2,2]])
A44 = np.array([[1,2,1,1],[2,1,3,1],[3,2,3,2],[3,5,1,2]])
A45 = np.array([[1,2,1,1],[2,1,3,1],[3,2,3,2],[3,5,1,2]])
A51 = np.array([[2,1,1,1],[1,3,1,1],[2,3,2,2],[1,1,4,3]])
A52 = np.array([[1,1,1,1],[2,3,1,1],[3,3,2,2],[4,1,4,3]])
A53 = np.array([[1,2,1,1],[2,1,1,1],[3,2,2,2],[4,1,4,3]])
A54 = np.array([[1,2,1,1],[2,1,3,1],[3,2,3,2],[4,1,1,3]])
A55 = np.array([[1,2,1,1],[2,1,3,1],[3,2,3,2],[4,1,1,4]])

det_11 = np.linalg.det(A11)
det_12 = np.linalg.det(A12)
det_13 = np.linalg.det(A13)
det_14 = np.linalg.det(A14)
det_15 = np.linalg.det(A15)
det_21 = np.linalg.det(A21)
det_22 = np.linalg.det(A22)
det_23 = np.linalg.det(A23)
det_24 = np.linalg.det(A24)
det_25 = np.linalg.det(A25)
det_31 = np.linalg.det(A31)
det_32 = np.linalg.det(A32)
det_33 = np.linalg.det(A33)
det_34 = np.linalg.det(A34)
det_35 = np.linalg.det(A35)
det_41 = np.linalg.det(A41)
det_42 = np.linalg.det(A42)
det_43 = np.linalg.det(A43)
det_44 = np.linalg.det(A44)
det_45 = np.linalg.det(A45)
det_51 = np.linalg.det(A51)
det_52 = np.linalg.det(A52)
det_53 = np.linalg.det(A53)
det_54 = np.linalg.det(A54)
det_55 = np.linalg.det(A55)

c11 = (-1)**(1+1) * det_11
c12 = (-1)**(1+2) * det_12
c13 = (-1)**(1+3) * det_13
c14 = (-1)**(1+4) * det_14
c15 = (-1)**(1+5) * det_15
c21 = (-1)**(2+1) * det_21
c22 = (-1)**(2+2) * det_22
c23 = (-1)**(2+3) * det_23
c24 = (-1)**(2+4) * det_24
c25 = (-1)**(2+5) * det_25
c31 = (-1)**(3+1) * det_31
c32 = (-1)**(3+2) * det_32
c33 = (-1)**(3+3) * det_33
c34 = (-1)**(3+4) * det_34
c35 = (-1)**(3+5) * det_35
c41 = (-1)**(4+1) * det_41
c42 = (-1)**(4+2) * det_42
c43 = (-1)**(4+3) * det_43
c44 = (-1)**(4+4) * det_44
c45 = (-1)**(4+5) * det_45
c51 = (-1)**(5+1) * det_51
c52 = (-1)**(5+2) * det_52
c53 = (-1)**(5+3) * det_53
c54 = (-1)**(5+4) * det_54
c55 = (-1)**(5+5) * det_55

a11 = matrix_A[0][0]
a12 = matrix_A[0][1]
a13 = matrix_A[0][2]
a14 = matrix_A[0][3]
a15 = matrix_A[0][4]
a21 = matrix_A[1][0]
a22 = matrix_A[1][1]
a23 = matrix_A[1][2]
a24 = matrix_A[1][3]
a25 = matrix_A[1][4]
a31 = matrix_A[2][0]
a32 = matrix_A[2][1]
a33 = matrix_A[2][2]
a34 = matrix_A[2][3]
a35 = matrix_A[2][4]
a41 = matrix_A[3][0]
a42 = matrix_A[3][1]
a43 = matrix_A[3][2]
a44 = matrix_A[3][3]
a45 = matrix_A[3][4]
a51 = matrix_A[4][0]
a52 = matrix_A[4][1]
a53 = matrix_A[4][2]
a54 = matrix_A[4][3]
a55 = matrix_A[4][4]

# Row 1
det_A_row1 = a11*c11 + a12*c12 + a13*c13 + a14*c14 + a15*c15
print(f"det A = {det_A_row1}")
# Row 2
det_A_row2 = a21*c21 + a22*c22 + a23*c23 + a24*c24 + a25*c25
print(f"det A = {det_A_row2}")
# Row 3
det_A_row3 = a31*c31 + a32*c32 + a33*c33 + a34*c34 + a35*c35
print(f"det A = {det_A_row3}")
# Row 4
det_A_row4 = a41*c41 + a42*c42 + a43*c43 + a44*c44 + a45*c45
print(f"det A = {det_A_row4}")
# Row 5
det_A_row5 = a51*c51 + a52*c52 + a53*c53 + a54*c54 + a55*c55
print(f"det A = {det_A_row5}")
print()
Kof_Matrix_A = np.array([[c11,c12,c13,c14,c15],[c21,c22,c23,c24,c25],[c31,c32,c33,c34,c35],[c41,c42,c43,c44,c45],[c51,c52,c53,c54,c55]])
print(f"Marix dengan anggota kofaktor-kofaktornya = \n{Kof_Matrix_A}")
print()
Trans_Kof_Matrix_A = Kof_Matrix_A.transpose()
print(f"Transpose Matrix dari kofaktornya = \n{Trans_Kof_Matrix_A}")
print()
invers_A = 1 / det_A_row1 * Trans_Kof_Matrix_A
print(f"Hasil Invers Matrix adalah = \n{invers_A.round(1)}")

Matrix A: 
[[1 2 1 1 1]
 [2 1 3 1 1]
 [3 2 3 2 2]
 [4 1 1 4 3]
 [3 5 1 2 2]]
pembuktian Determinan= -5.000000000000011
pembuktian Invers = 
[[-1.8  0.2  0.2 -0.   0.6]
 [ 0.4  0.4 -0.6 -0.   0.2]
 [ 0.6  0.6 -0.4 -0.  -0.2]
 [ 2.   3.  -4.   1.  -0. ]
 [-0.6 -4.6  5.4 -1.  -0.8]]

det A = -5.000000000000031
det A = -4.9999999999999964
det A = -1.0
det A = -5.0
det A = -4.999999999999998

Marix dengan anggota kofaktor-kofaktornya = 
[[ 9.00000000e+00 -2.00000000e+00 -3.00000000e+00 -1.00000000e+01
   3.00000000e+00]
 [-1.00000000e+00 -2.00000000e+00 -3.00000000e+00 -1.50000000e+01
   2.30000000e+01]
 [ 7.00000000e+00  3.00000000e+00 -2.00000000e+00  4.00000000e+00
  -1.50000000e+01]
 [-0.00000000e+00  0.00000000e+00 -0.00000000e+00 -5.00000000e+00
   5.00000000e+00]
 [-3.00000000e+00 -1.00000000e+00  1.00000000e+00  3.55271368e-15
   4.00000000e+00]]

Transpose Matrix dari kofaktornya = 
[[ 9.00000000e+00 -1.00000000e+00  7.00000000e+00 -0.00000000e+00
  -3.00000000e+00]
 [-2.00000000e+